# Generated by Django 4.2.6 on 2023-11-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrilliantPrinters_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="Text_files")),
            ],
        ),
    ]
