# Generated by Django 4.2.6 on 2023-11-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrilliantPrinters_app", "0002_textfile"),
    ]

    operations = [
        migrations.DeleteModel(name="TextFile",),
        migrations.AddField(
            model_name="question",
            name="file",
            field=models.FileField(null=True, upload_to="Text_files"),
        ),
    ]
