# Generated by Django 4.2.6 on 2023-11-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrilliantPrinters_app', '0002_alter_questionfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
