# Generated by Django 4.2.6 on 2023-11-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BrilliantPrinters_app', '0002_remove_question_files_questionfile_filerespondent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='respondent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BrilliantPrinters_app.respondent'),
        ),
        migrations.AlterField(
            model_name='questionfile',
            name='fileRespondent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BrilliantPrinters_app.respondent'),
        ),
    ]
