# Generated by Django 4.2.6 on 2023-11-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BrilliantPrinters_app", "0002_alter_questionfile_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="files",),
        migrations.AddField(
            model_name="questionfile",
            name="parentQuestion",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="BrilliantPrinters_app.question",
            ),
        ),
        migrations.AlterField(
            model_name="questionfile",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/%Y/%m"),
        ),
    ]
