# Generated by Django 4.2.6 on 2023-11-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "BrilliantPrinters_app",
            "0003_remove_question_files_questionfile_parentquestion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionfile",
            name="parentQuestion",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="BrilliantPrinters_app.question",
            ),
            preserve_default=False,
        ),
    ]
