# Generated by Django 4.2.6 on 2023-11-21 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BrilliantPrinters_app", "0003_delete_textfile_question_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(null=True, upload_to="Text_files")),
            ],
        ),
        migrations.RemoveField(model_name="question", name="file",),
        migrations.AddField(
            model_name="question",
            name="files",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="BrilliantPrinters_app.questionfile",
            ),
        ),
    ]
