# Generated by Django 4.2.6 on 2023-11-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BrilliantPrinters_app", "0004_alter_questionfile_parentquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionfile",
            name="parentQuestion",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="BrilliantPrinters_app.question",
            ),
        ),
    ]
