# Generated by Django 4.2.6 on 2023-11-21 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BrilliantPrinters_app", "0005_alter_question_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="files",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="BrilliantPrinters_app.questionfile",
            ),
        ),
    ]
