# Generated by Django 4.2.6 on 2023-11-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BrilliantPrinters_app", "0005_alter_questionfile_parentquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionfile",
            name="fileRespondent",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="BrilliantPrinters_app.respondent",
            ),
        ),
    ]
